import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Hero from '@/components/hero'
import Plans from '@/components/plans'
import Experience from '@/components/experience'
import App from '@/components/app'
import Transparency from '@/components/transparency'
import Represent from '@/components/represent'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-gray-900">
          <Hero />
          <Plans />
          <App />
          <Transparency />
          <Represent />
          <Experience />
        </div>
      </main>
    </>
  )
}
